from model.base_model import Course

# -----------------------------
# Mock Data
# -----------------------------
courses = [
    Course(
        id=1,
        title="Computer Science BSc",
        university="University of Oxford",
        duration="3 years",
        location="Oxford, UK",
        fees="£9,250 per year",
        description="A comprehensive introduction to computer science covering algorithms, data structures, and programming fundamentals. This course provides a solid foundation for advanced computer science studies.",
        requirements=["High school mathematics", "Basic logical reasoning skills"],
        schedule="Monday, Wednesday, Friday 10:00-11:30 AM",
        instructor="Dr. Sarah Chen",
        credits=4,
    ),
    Course(
        id=2,
        title="Mechanical Engineering MSc",
        university="MIT",
        duration="2 years",
        location="Cambridge, MA, USA",
        fees="$25,000 per year",
        description="Focuses on advanced mechanical design, thermodynamics, and robotics for innovative engineering solutions.",
        requirements=["Bachelor’s degree in Mechanical Engineering", "Calculus and Physics background"],
        schedule="Tuesday & Thursday 2:00-4:00 PM",
        instructor="Prof. Daniel Wright",
        credits=5,
    ),
    Course(
        id=3,
        title="Business Administration MBA",
        university="Harvard University",
        duration="2 years",
        location="Boston, MA, USA",
        fees="$60,000 per year",
        description="An intensive MBA program focusing on strategic management, finance, leadership, and global business practices.",
        requirements=["Undergraduate degree in any discipline", "2+ years work experience"],
        schedule="Monday–Friday 9:00 AM-12:00 PM",
        instructor="Prof. Emily Johnson",
        credits=6,
    ),
    Course(
        id=4,
        title="Artificial Intelligence MSc",
        university="Stanford University",
        duration="1 year",
        location="Stanford, CA, USA",
        fees="$35,000 total",
        description="Covers deep learning, natural language processing, and computer vision, preparing students for cutting-edge AI research.",
        requirements=["Bachelor’s in Computer Science or related field", "Python programming proficiency"],
        schedule="Monday, Wednesday 3:00-5:00 PM",
        instructor="Dr. Kevin Liu",
        credits=5,
    ),
    Course(
        id=5,
        title="Architecture BA",
        university="ETH Zurich",
        duration="3 years",
        location="Zurich, Switzerland",
        fees="CHF 1,500 per semester",
        description="Foundations of architectural design, construction methods, and sustainable building practices.",
        requirements=["Portfolio of previous design work", "High school diploma"],
        schedule="Tuesday & Thursday 10:00 AM-12:30 PM",
        instructor="Prof. Laura Steiner",
        credits=4,
    ),
    Course(
        id=6,
        title="Environmental Engineering BEng",
        university="University of Toronto",
        duration="4 years",
        location="Toronto, Canada",
        fees="CAD 9,800 per year",
        description="Focuses on water treatment, waste management, and renewable energy technologies for a sustainable future.",
        requirements=["High school chemistry and physics", "Mathematics Level II"],
        schedule="Monday, Wednesday, Friday 11:00 AM-12:30 PM",
        instructor="Dr. Anthony Brown",
        credits=4,
    ),
    Course(
        id=7,
        title="Cybersecurity MSc",
        university="Carnegie Mellon University",
        duration="1.5 years",
        location="Pittsburgh, PA, USA",
        fees="$40,000 total",
        description="Teaches ethical hacking, cryptography, network defense, and incident response with hands-on labs.",
        requirements=["Bachelor’s degree in Computer Science", "Knowledge of networks and Linux OS"],
        schedule="Tuesday & Thursday 5:00-7:00 PM",
        instructor="Dr. Rajesh Kumar",
        credits=5,
    ),
    Course(
        id=8,
        title="International Relations BA",
        university="King’s College London",
        duration="3 years",
        location="London, UK",
        fees="£9,500 per year",
        description="Explores global politics, diplomacy, and conflict resolution in an interconnected world.",
        requirements=["High school history and English proficiency"],
        schedule="Monday & Wednesday 2:00-4:00 PM",
        instructor="Prof. Helena Carter",
        credits=3,
    ),
    Course(
        id=9,
        title="Psychology BSc",
        university="University of Melbourne",
        duration="3 years",
        location="Melbourne, Australia",
        fees="AUD 8,200 per semester",
        description="Provides an in-depth understanding of human behavior, cognition, and emotional development.",
        requirements=["High school biology", "Interest in mental health studies"],
        schedule="Tuesday & Thursday 11:00 AM-1:00 PM",
        instructor="Dr. Olivia White",
        credits=4,
    ),
    Course(
        id=10,
        title="Data Science MSc",
        university="Columbia University",
        duration="1.5 years",
        location="New York, NY, USA",
        fees="$38,000 total",
        description="Covers machine learning, big data analytics, and visualization tools for actionable business insights.",
        requirements=["Bachelor’s in STEM field", "Basic Python and Statistics"],
        schedule="Monday, Wednesday, Friday 4:00-5:30 PM",
        instructor="Prof. Marcus Allen",
        credits=5,
    ),
    Course(
        id=11,
        title="Renewable Energy Engineering MSc",
        university="Technical University of Denmark",
        duration="2 years",
        location="Lyngby, Denmark",
        fees="DKK 24,000 per semester",
        description="Teaches sustainable energy solutions including solar, wind, and bioenergy technologies.",
        requirements=["Bachelor’s degree in Engineering", "Calculus and Physics background"],
        schedule="Tuesday & Thursday 9:00-11:00 AM",
        instructor="Dr. Lars Hansen",
        credits=5,
    ),
    Course(
        id=12,
        title="Digital Marketing Strategies",
        university="University of Sydney",
        duration="10 weeks",
        location="Sydney, Australia",
        fees="AUD 3,700",
        description="Introduces modern digital marketing strategies like SEO, content creation, and social media advertising.",
        requirements=["Basic computer literacy"],
        schedule="Monday & Wednesday 4:00-6:00 PM",
        instructor="Dr. Mia Turner",
        credits=3,
    ),
    Course(
        id=13,
        title="Film and Media Studies BA",
        university="New York University",
        duration="3 years",
        location="New York, NY, USA",
        fees="$22,000 per year",
        description="Covers film history, production techniques, and media theory with hands-on projects.",
        requirements=["Portfolio or previous creative work"],
        schedule="Tuesday & Thursday 1:00-3:00 PM",
        instructor="Prof. Sophia Green",
        credits=3,
    ),
    Course(
        id=14,
        title="Advanced Algorithms MSc",
        university="California Institute of Technology",
        duration="1 year",
        location="Pasadena, CA, USA",
        fees="$30,000 total",
        description="Focuses on the design and analysis of advanced algorithms including graph theory and dynamic programming.",
        requirements=["Bachelor’s in Computer Science", "Strong math background"],
        schedule="Monday & Wednesday 2:00-4:00 PM",
        instructor="Dr. Michael Evans",
        credits=5,
    ),
    Course(
        id=15,
        title="Modern Art History",
        university="University of Paris",
        duration="8 weeks",
        location="Paris, France",
        fees="€2,500",
        description="Explores key modern art movements such as Impressionism, Cubism, and Surrealism.",
        requirements=["Interest in art or history"],
        schedule="Wednesday & Friday 3:00-5:00 PM",
        instructor="Prof. Isabelle Dupont",
        credits=2,
    ),
    Course(
        id=16,
        title="Marine Biology BSc",
        university="University of Cape Town",
        duration="3 years",
        location="Cape Town, South Africa",
        fees="ZAR 60,000 per year",
        description="Studies ocean ecosystems, marine species, and conservation techniques with fieldwork components.",
        requirements=["High school biology and chemistry"],
        schedule="Monday, Wednesday, Friday 8:00-9:30 AM",
        instructor="Dr. Thabo Ndlovu",
        credits=4,
    ),
    Course(
        id=17,
        title="Game Development MSc",
        university="University of Edinburgh",
        duration="1.5 years",
        location="Edinburgh, Scotland",
        fees="£14,000 total",
        description="Covers game design, 3D graphics, and interactive storytelling with Unity and Unreal Engine.",
        requirements=["Bachelor’s in Computer Science or related field"],
        schedule="Tuesday & Thursday 6:00-8:00 PM",
        instructor="Prof. Hannah Clarke",
        credits=5,
    ),
    Course(
        id=18,
        title="Health Informatics MSc",
        university="Johns Hopkins University",
        duration="1 year",
        location="Baltimore, MD, USA",
        fees="$28,000 total",
        description="Combines healthcare and data science to improve patient care through electronic health records and analytics.",
        requirements=["Bachelor’s in Health Sciences or IT field"],
        schedule="Monday & Wednesday 5:00-7:00 PM",
        instructor="Dr. Laura Smith",
        credits=4,
    ),
]
